name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        include:
        - name: Windows
          os: windows-latest
          mill: 'mill --no-server'
        - name: Linux
          os: ubuntu-latest
          mill: 'mill'
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      name: "Set up Mill"
      with:
        mill-version: 0.8.0
    - name: "Run Mill"
      run: ${{ matrix.mill }} version

